FROM node:12-stretch-slim AS base
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY .npmrc .npmrc 
RUN npm install -g firebase-tools

# ---- Dependencies ----
FROM base AS dependencies
# install node packages
COPY package.json package.json
RUN npm set progress=false && npm config set depth 0
RUN npm install --only=production 
RUN rm -f .npmrc


FROM base AS dependencies_dev
# install node packages
COPY package.json package.json
RUN npm set progress=false && npm config set depth 0
RUN npm install --silent
RUN rm -f .npmrc

FROM base as production
COPY --from=dependencies /usr/src/app/node_modules ./node_modules
COPY --from=dependencies /usr/src/app/package.json ./package.json
COPY --from=dependencies /usr/src/app/package-lock.json ./package-lock.json
ADD src /usr/src/app/src
CMD npm run start


FROM base as dev
COPY --from=dependencies_dev /usr/src/app/node_modules ./node_modules
RUN npm install nodemon -g
COPY package.json package.json