version: "3"

services:
  db:
    image: "mongo:latest"
    networks:
      - default
    ports:
      - "27017:27017"
  competencias:
    image: "nodejs:latest"
    environment:
      NODE_ENV: production
      RUTA: competencias
    networks:
      - default
    depends_on:
      - "db"
